Utilize TSAI tiler to crop out FOVs
angelolab/maldi-tools pull request #20
Opened 2023-11-16 23:23 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #12.

**How did you implement your changes**

Using the `.imzml` file, and combined with the output from TSAI:

1. Assign each scanned coordinate on the slide to their respective core, as labeled by TSAI
2. Use the coordinates to crop out the FOVs

**Remaining issues**

Currently, `generate_glycan_mask` segments out all of the cores at once. The result of `map_coordinates_to_core_name`, however, can be used to segment out individual cores. We still need to update `generate_glycan_mask` to handle individual core segmentation.

2023-11-21 20:12 UTC, srivarra requested changes
Just one small aesthetic thing, and a question about `"Z"` coordinates.

2023-11-21 20:12 UTC, srivarra commented on conftest.py
> +        np.random.rand(len(imz_data.coordinates) + 2, len(columns_write)), columns=columns_write
I believe `np.random.default_rng` is the recommended way to generate random numbers in NumPy as of late.

We can use the `rng` fixture to generate the random data 

```python
rng.random(size=(len(imz_data.coordinates) + 2, len(columns_write))]
```

2023-11-21 20:12 UTC, srivarra commented on src/maldi_tools/extraction.py
> +        names=["Date", "Time", "Region", "PosX", "PosY", "X", "Y", "Z"],
Do we need to read in the `"Z"` coordinate?

2023-11-21 20:15 UTC, srivarra commented on templates/maldi-pipeline.ipynb
>    {
<pre class="ql-syntax" spellcheck="false">Line #5.    # cores_to_crop = region_core_info["Core"].unique().tolist()
</pre><p>We can make this a bit easier for the user, maybe inside the <code>extraction.generate_glycan_mask</code> function allow <code>cores_to_crop</code> to optionally be <code>"all"</code> and we can move this complexity into the function.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/maldi-tools/pull/20/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='56'/>

2023-11-21 22:35 UTC, srivarra approved these changes
Looks good to me!

2023-11-28 23:25 UTC, alex-l-kong commented
@kxleow ran into a case where multiple slides need to be supported. That is currently not the case, as we assume the user has only one poslog file per run. This will need to be added into the pipeline.

2023-11-29 22:28 UTC, alex-l-kong commented
Cropping now supports multiple poslog files.

2024-08-08 20:53 UTC, kxleow commented
find nearest neighbour pixel
veri

2024-08-08 21:34 UTC, kxleow commented
Alternative to using poslog and imzml for core cropping:
1. Use imageJ to segment/split up cores into individual binary masks
2. Then use centroids in json to assign core name or positions to each mask
3. Output table - a column with mask ids and a column with corresponding core names

Sub-issue: Find nearest neighbours if centroid not found

2024-09-17 18:19 UTC, kxleow commented
Ran into a case with >4 TMAs combined and the order of TMAs did not follow a sequential order in the image (left-right or top-bottom). The order of TMAs were found in the warnings generated at the core cropping step.

2024-11-11 20:51 UTC, alex-l-kong commented
> Ran into a case with >4 TMAs combined and the order of TMAs did not follow a sequential order in the image (left-right or top-bottom). The order of TMAs were found in the warnings generated at the core cropping step.

@kxleow the updated spectra extractor will prevent this issue from popping up once that gets merged in.

2024-11-11 23:03 UTC, merged